user "root";
private_key "/root/.ssh/id_rsa";
public_key "/root/.ssh/id_rsa.pub";
key_auth;

group martobre => "192.168.0.151";

use config;
use install;
use init;

require Rex::Logger;
require communication;

require Service::aliases;
require Service::apache;
require Service::apache::php;
require Service::apache::vhost;
require Service::crontask;
require Service::dovecot;
require Service::drbd;
require Service::fail2ban;
require Service::git;
require Service::lamadmin;
require Service::mailman;
require Service::mailman::maillinglist;
require Service::mysql;
require Service::nfs;
require Service::ntp;
require Service::pacemaker;
require Service::pacemaker::clone;
require Service::pacemaker::colocation;
require Service::pacemaker::globfunc;
require Service::pacemaker::group;
require Service::pacemaker::location;
require Service::pacemaker::master;
require Service::pacemaker::order;
require Service::pacemaker::primitive;
require Service::pacemaker::property;
require Service::pacemaker::rsc_defaults;
require Service::pacemaker::service;
require Service::phpmyadmin;
require Service::postfix;
require Service::resolver;
require Service::ssh;
require Service::unison;
require Service::uptime;
require Service::user;
require Service::webrss2email;

task "configure", group => martobre, sub{

  initialise();

	Service::apache::define({

	});

	Service::apache::php::define({

	});

	Service::apache::vhost::define({

		'file_name' => 'adminPannel',
		'server_name' => 'www.testounet.fr',
		'port' => '80',
		'server_admin' => 'karlito@martobre.fr',
		'docroot' => '/etc/lamamos/admin_panel/',
		'docroot_owner' => 'www-data',
		'docroot_group' => 'www-data',
		'ssl' => '0',
		'ssl_cert_dir' => '',
		'manage_folder' => '0',
		'docroot_mode' => '',
		'after' => '',
	});

	Service::lamadmin::define({

		'install_path' => '/etc/lamamos/admin_panel/',
	});

	Service::ntp::define({

	});

	Service::resolver::define({

		'domain_name' => 'testounet.fr',
		'search_path' => ['testounet.fr'],
		'name_servers' => ['208.67.222.222', '208.67.220.220'],
	});

	Service::user::define({

		'name' => 'karlito',
		'home' => '/home/karlito',
		'password' => 'none',
		'shell' => '/bin/bash',
		'systeme' => '1',
		'no_create_home' => '1',
	});

  finalise();
};

