#! /bin/sh
### BEGIN INIT INFO
# Provides:          lamamos
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: lamamos
# Description:       launch a rex configure
### END INIT INFO

# /etc/init.d/lamamos
#

# Some things that run always
#touch /var/lock/blah

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting rex configure"
    cd /etc/lamamos/rex/
    rex configure
    ;;
  stop)
    echo "didn't do anything"
    ;;
  *)
    echo "Usage: /etc/init.d/lamamos {start|stop}"
    exit 1
    ;;
esac

exit 0
